// src\utils\suburbs.js
export const suburbsList = [
    "Rondebosch",
    "Newlands",
    "Kommetjie",
    "Oranjezicht",
    "Sea Point",
    "Claremont",
    "Constantia",
    "Camps Bay",
    "Green Point",
    "Milnerton",
    "Muizenberg",
    "Durbanville",
    "Simon's Town",
    "Bellville",
    "Parklands",
    "Salt River",
    "Atlantis",
    "Brackenfell",
    "Gardens",
    "Observatory",
    "Vredehoek",
    "Tamboerskloof",
    "Kenilworth",
    "Mowbray",
    "Bergvliet",
    "Woodstock",
    "Goodwood",
    "Kloof Nek",
    "Belhar",
    "Fordsburg"
  ];